spring:
    application:
        name: linkfamily
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/family_link
        username: root
        password: Xjs1234560

# 配置 mybatis-plus
mybatis-plus:
  type-aliases-package: com.example.linkfamily.Model.Entity # 实体类所在的包，允许用实体类类名作为别名
  mapper-locations: classpath:Mapper/*.xml # Mapper XML文件位置

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置日志
    map-underscore-to-camel-case: true # 类属性与表字段的驼峰映射

  global-config:
    db-config: # 数据库配置
      table-prefix: tb_  # 表名前缀为tb_，表名为前缀连接类名（小写）

minio:
  endpoint: http://192.168.1.104:9000 # 修改你的 MinIO 端点
  accessKey: minioadmin # 修改你的 MinIO Access Key
  secretKey: minioadmin # 修改你的 MinIO Secret Key
  bucket: family-link # 确认 Bucket 名称与你创建的一致

